config/routes.rb
Saint::Application.routes.draw do

  match '/signin',		to: 'sessions#new'
  match '/signout',		to: 'sessions#destroy', via: :delete
  match '/dashboard',	to: 'dashboard_trended_metrics#index'

  resources :cloud_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end

  resources :clouds

  resources :brand_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end
  
  resources :classifications do
    collection do
      get 'run'
    end
    member do
      get 'run'
    end
  end
  
  resources :sites

  resources :suites
  
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :dashboard_trended_metrics do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_driver_types do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_browsers do
    collection do
      get 'visits'
    end
  end
  
  resources :dashboard_clouds do
    collection do
      get 'page_views'
      get 'form_completes'
    end
  end
  
  resources :dashboard_offer_types do
    collection do
      get 'form_views'
      get 'form_completes'
      get 'form_complete_rate'
    end
  end
  
  resources :dashboard_video_names do
    collection do
      get 'video_starts'
      get 'video_completes'
    end
  end
  
  root :to => 'classifications#index'

end

app/models/cloud_match.rb
class CloudMatch < ActiveRecord::Base
  attr_accessible :match_list, :cloud_id, :position
  belongs_to :cloud
  before_save :prep_list_for_save
  
  validates :match_list, presence:true
  validates :cloud_id, presence:true
  
  def prep_list_for_save
    self.match_list = self.match_list.gsub("\n", ",").gsub("\r", "") if !self.match_list.nil?
  end
  
  def prep_list_for_form
    match_list = self.match_list.gsub(",", "\r\n") if !self.match_list.nil?
  end
  
  def prep_list_for_display
    match_list = self.match_list.gsub(",", "<br>").html_safe if !self.match_list.nil?
  end
end

app/controllers/cloud_matches_controller.rb
class CloudMatchesController < ApplicationController
  def index
    @cloud_matches = CloudMatch.order('cloud_matches.position ASC, id')
  end

  def new
    @cloud_match = CloudMatch.new
  end

  def edit
    @cloud_match = CloudMatch.find(params[:id])
    @cloud_match.match_list = @cloud_match.prep_list_for_form
  end

  def create
    @cloud_match = CloudMatch.new(params[:cloud_match])
    @cloud_match.position = CloudMatch.all.length + 1 if @cloud_match.position.nil?
    
    if @cloud_match.save
      flash[:success] = 'Match has been successfully created.'
      redirect_to cloud_matches_path
    else
      render 'new'
    end
  end

  def update
    @cloud_match = CloudMatch.find(params[:id])
    @cloud_match.position = CloudMatch.all.length + 1 if @cloud_match.position.nil?
    
    if @cloud_match.update_attributes(params[:cloud_match])
      flash[:success] = 'Match has been successfully updated.'
      redirect_to cloud_matches_path
    else
      render 'edit'
    end
  end

  def destroy
    @cloud_match = CloudMatch.find(params[:id])
    @cloud_match.destroy
    
    flash[:success] = 'Match has been successfully deleted.'
    redirect_to cloud_matches_path
  end
  
  def upload
    @upload_file = UploadFile.new
  end
  
  def process_upload
    @upload_file = UploadFile.new
    if !params[:upload_file].nil?
      @upload_file.filename = params[:upload_file][:filename].original_filename
      @path = @upload_file.save_file(params[:upload_file][:filename])
    end
    
    if @upload_file.save && @path
      require 'csv'
      
      count = 0
      deleted = false
      CSV.foreach(@path, :col_sep => ",") do |row|
        # skip column headings
        if count != 0
          match = CloudMatch.new
          match.match_list = row[0]
          match.cloud_id = Cloud.find_by_name(row[1]).nil? ? nil : Cloud.find_by_name(row[1]).id
          if match.valid?
            if !deleted
              # start all over
              CloudMatch.destroy_all
              deleted = true
            end
            match.position = CloudMatch.count + 1
            match.save
          end
        end
        count += 1
      end
      
      flash[:success] = "Your file was uploaded successfully!"
      redirect_to cloud_matches_path
    else
      render "upload"
    end
  end
  
  def sort
    @cloud_matches = CloudMatch.all
    @cloud_matches.each do |match|
      match.position = params['match'].index(match.id.to_s) + 1
      match.save
    end
  
    render nothing: true
  end
end

app/views/cloud_matches/_button-nav.html.erb
<div class="button-nav">
	<%= link_to "Add new cloud match", new_cloud_match_path, class: "btn btn-large btn-primary" %>
	<%= link_to "Save sort order", "#", class: "btn btn-large btn-primary save-sort", rel: (url_for sort_cloud_matches_path) %>
	<%= link_to "Upload new match list", upload_cloud_matches_path, class: "btn btn-large btn-primary" %>
</div>

app/views/cloud_matches/_cloud_match.html.erb
<tr id="match_<%= cloud_match.id %>">
	<td><%= cloud_match.position.nil? ? '--' : cloud_match.position %></td>
	<td><%= cloud_match.prep_list_for_display %></td>
	<td><%= cloud_match.cloud.name %></td>
	<td>
		<%= link_to 'edit', edit_cloud_match_path(cloud_match) %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to 'delete', cloud_match, confirm: 'Are you sure?', method: :delete %>
	</td>
</tr>

app/views/cloud_matches/_form.html.erb
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@cloud_match) do |f| %>
			<%= render 'shared/error_messages', obj:@cloud_match %>

			<div class="field">
				<%= f.label :cloud_id %>
			    <%= f.select :cloud_id, Cloud.order(:name).collect {|c| [ c.name, c.id ] }, {:include_blank => "Please choose one"} %>
			</div>
			<div class="field">
				<%= f.label 'Match list (put each on a new line)' %>
				<%= f.text_area :match_list %>
			</div>
			
			<div class="actions">
				<%= f.submit lbl, class:'btn btn-large btn-primary' %>
			</div>
		<% end %>
	</div>
</div>

app/views/cloud_matches/edit.html.erb
<%= provide(:title, 'Change cloud match') %>
<h1>Change cloud match</h1>

<%= render 'form', lbl:'Save changes' %>

app/views/cloud_matches/index.html.erb
<%= provide(:title, 'All cloud matches') %>

<div id="save-alert" class="alert alert-success"></div>
<h1>All cloud matches</h1>
<p>The priority order of the match list can be sorted using drag &amp; drop. Just click "Save sort order" to save your changes.</p>

<%= render 'button-nav' %>

<table class="data sortable" cellpadding="0" cellspacing="0" border="0">
	<thead>
		<tr>
			<th>Match</th>
			<th>Match list</th>
			<th>Cloud</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<%= render @cloud_matches %>
	</tbody>
</table>

<%= render 'button-nav' %>

app/views/cloud_matches/new.html.erb
<%= provide(:title, 'Add new match') %>
<h1>Add new match</h1>

<%= render 'form', lbl:'Add match' %>

app/views/cloud_matches/upload.html.erb
<% provide(:title, "Upload new cloud match file") %>
<h1>Upload new cloud match file</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_tag(process_upload_cloud_matches_path, multipart:true) do %>
			<%= render 'shared/error_messages', obj:@upload_file %>

			<div class="field">
				<%= label_tag "upload_file_filename", "Upload CSV file", class:"inline" %>&nbsp;(<%= link_to "see template", "/templates/cloud_matches.csv" %>)
				<%= file_field 'upload_file', 'filename' %>
			</div>
		
			<div class="action">
				<%= submit_tag("Upload file", class: "btn btn-large btn-primary") %>
			</div>
		<% end %>
	</div>
</div>