config/routes.rb
Saint::Application.routes.draw do

  match '/signin',		to: 'sessions#new'
  match '/signout',		to: 'sessions#destroy', via: :delete
  match '/dashboard',	to: 'dashboard_trended_metrics#index'

  resources :cloud_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end

  resources :clouds

  resources :brand_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end
  
  resources :classifications do
    collection do
      get 'run'
    end
    member do
      get 'run'
    end
  end
  
  resources :sites

  resources :suites
  
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :dashboard_trended_metrics do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_driver_types do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_browsers do
    collection do
      get 'visits'
    end
  end
  
  resources :dashboard_clouds do
    collection do
      get 'page_views'
      get 'form_completes'
    end
  end
  
  resources :dashboard_offer_types do
    collection do
      get 'form_views'
      get 'form_completes'
      get 'form_complete_rate'
    end
  end
  
  resources :dashboard_video_names do
    collection do
      get 'video_starts'
      get 'video_completes'
    end
  end
  
  root :to => 'classifications#index'

end

app/models/cloud.rb
class Cloud < ActiveRecord::Base
  has_many :cloud_matches, :dependent => :destroy
  
  validates :name, presence:true
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
  def index
    @clouds = Cloud.paginate(page: params[:page])
  end

  def new
    @cloud = Cloud.new
  end

  def edit
    @cloud = Cloud.find(params[:id])
  end

  def create
    @cloud = Cloud.new(params[:cloud])
    
    if @cloud.save
      flash[:success] = 'Cloud (' + params[:cloud][:name] + ') has been successfully created.'
      redirect_to clouds_path
    else
      render 'new'
    end
  end

  def update
    @cloud = Cloud.find(params[:id])
    
    if @cloud.update_attributes(params[:cloud])
      flash[:success] = 'Cloud (' + params[:cloud][:name] + ') has been successfully updated.'
      redirect_to clouds_path
    else
      render 'edit'
    end
  end

  def destroy
    @cloud = Cloud.find(params[:id])
    @cloud.destroy
    
    flash[:success] = 'Cloud (' + @cloud.name + ') and all matches have been successfully deleted.'
    redirect_to clouds_path
  end
end

app/views/clouds/_button-nav.html.erb
<div class="button-nav">
	<%= link_to "Add new cloud", new_cloud_path, class: "btn btn-large btn-primary" %>
</div>

app/views/clouds/_cloud.html.erb
<tr>
	<td><%= cloud.name %></td>
	<td>
		<%= link_to 'edit', edit_cloud_path(cloud) %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to 'delete', cloud, confirm: 'Are you sure?', method: :delete %>
	</td>
</tr>

app/views/clouds/_form.html.erb
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@cloud) do |f| %>
			<%= render 'shared/error_messages', obj:@cloud %>

			<div class="field">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>
			<div class="actions">
				<%= f.submit lbl, class:'btn btn-large btn-primary' %>
			</div>
		<% end %>
	</div>
</div>

app/views/clouds/edit.html.erb
<%= provide(:title, 'Change cloud') %>
<h1>Change cloud</h1>

<%= render 'form', lbl:'Save changes' %>

app/views/clouds/index.html.erb
<%= provide(:title, 'All clouds') %>
<h1>All clouds</h1>

<%= render 'button-nav' %>

<%= will_paginate %>

<table class="data" cellpadding="0" cellspacing="0" border="0">
	<tr>
		<th>Cloud name</th>
		<th>&nbsp;</th>
	</tr>
	<%= render @clouds %>
</table>

<%= will_paginate %>

<%= render 'button-nav' %>

app/views/clouds/new.html.erb
<%= provide(:title, 'Add new cloud') %>
<h1>Add new cloud</h1>

<%= render 'form', lbl:'Add cloud' %>