config/routes.rb
Saint::Application.routes.draw do

  match '/signin',		to: 'sessions#new'
  match '/signout',		to: 'sessions#destroy', via: :delete
  match '/dashboard',	to: 'dashboard_trended_metrics#index'

  resources :cloud_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end

  resources :clouds

  resources :brand_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end
  
  resources :classifications do
    collection do
      get 'run'
    end
    member do
      get 'run'
    end
  end
  
  resources :sites

  resources :suites
  
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :dashboard_trended_metrics do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_driver_types do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_browsers do
    collection do
      get 'visits'
    end
  end
  
  resources :dashboard_clouds do
    collection do
      get 'page_views'
      get 'form_completes'
    end
  end
  
  resources :dashboard_offer_types do
    collection do
      get 'form_views'
      get 'form_completes'
      get 'form_complete_rate'
    end
  end
  
  resources :dashboard_video_names do
    collection do
      get 'video_starts'
      get 'video_completes'
    end
  end
  
  root :to => 'classifications#index'

end

app/models/brand_match.rb
class BrandMatch < ActiveRecord::Base
  attr_accessible :match_list, :exclude_list, :position
  before_save :prep_match_for_save
  before_save :prep_exclude_for_save
  
  validates :match_list, presence:true
  
  def prep_match_for_save
    self.match_list = self.match_list.gsub("\n", ",").gsub("\r", "") if !self.match_list.nil?
  end
  
  def prep_match_for_form
    match_list = self.match_list.gsub(",", "\r\n") if !self.match_list.nil?
  end
  
  def prep_match_for_display
    match_list = self.match_list.gsub(",", "<br>").html_safe if !self.match_list.nil?
  end
  
  def prep_exclude_for_save
    self.exclude_list = self.exclude_list.gsub("\n", ",").gsub("\r", "") if !self.exclude_list.nil?
  end
  
  def prep_exclude_for_form
    exclude_list = self.exclude_list.gsub(",", "\r\n") if !self.exclude_list.nil?
  end
  
  def prep_exclude_for_display
    exclude_list = self.exclude_list.gsub(",", "<br>").html_safe if !self.exclude_list.nil?
  end
end

app/controllers/brand_matches_controller.rb
class BrandMatchesController < ApplicationController
  def index
    @brand_matches = BrandMatch.order('brand_matches.position ASC, id')
  end

  def new
    @brand_match = BrandMatch.new
  end

  def edit
    @brand_match = BrandMatch.find(params[:id])
    @brand_match.match_list = @brand_match.prep_match_for_form
    @brand_match.exclude_list = @brand_match.prep_exclude_for_form
  end

  def create
    @brand_match = BrandMatch.new(params[:brand_match])
    @brand_match.position = BrandMatch.count + 1 if @brand_match.position.nil?
    
    if @brand_match.save
      flash[:success] = 'Match has been successfully created.'
      redirect_to brand_matches_path
    else
      render 'new'
    end
  end

  def update
    @brand_match = BrandMatch.find(params[:id])
    @brand_match.position = BrandMatch.count + 1 if @brand_match.position.nil?

    if @brand_match.update_attributes(params[:brand_match])
      flash[:success] = 'Match has been successfully updated.'
      redirect_to brand_matches_path
    else
      render 'edit'
    end
  end

  def destroy
    BrandMatch.find(params[:id]).destroy

    flash[:success] = 'Match has been successfully deleted.'
    redirect_to brand_matches_path
  end
  
  def upload
    @upload_file = UploadFile.new
  end
  
  def process_upload
    @upload_file = UploadFile.new
    if !params[:upload_file].nil?
      @upload_file.filename = params[:upload_file][:filename].original_filename
      @path = @upload_file.save_file(params[:upload_file][:filename])
    end
    
    if @upload_file.save && @path
      require 'csv'
      
      count = 0
      deleted = false
      CSV.foreach(@path, :col_sep => ",") do |row|
        # skip column headings
        if count != 0
          match = BrandMatch.new
          match.match_list = row[0]
          match.exclude_list = row[1]
          if match.valid?
            if !deleted
              # start all over
              BrandMatch.destroy_all
              deleted = true
            end
            match.position = BrandMatch.count + 1
            match.save
          end
        end
        count += 1
      end
      
      #delete file
      
      flash[:success] = "Your file was uploaded successfully!"
      redirect_to brand_matches_path
    else
      render "upload"
    end
  end
  
  def sort
    @brand_matches = BrandMatch.all
    @brand_matches.each do |match|
      match.position = params['match'].index(match.id.to_s) + 1
      match.save
    end
  
    render nothing: true
  end
end

app/views/brand_matches/_brand_match.html.erb
<tr id="match_<%= brand_match.id %>">
	<td><%= brand_match.position.nil? ? '--' : brand_match.position %></td>
	<td><%= brand_match.prep_match_for_display %></td>
	<td><%= brand_match.prep_exclude_for_display %></td>
	<td>
		<%= link_to 'edit', edit_brand_match_path(brand_match) %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to 'delete', brand_match, confirm: 'Are you sure?', method: :delete %>
	</td>
</tr>

app/views/brand_matches/_button-nav.html.erb
<div class="button-nav">
	<%= link_to "Add new brand match", new_brand_match_path, class: "btn btn-large btn-primary" %>
	<%= link_to "Save sort order", "#", class: "btn btn-large btn-primary save-sort", rel: (url_for sort_brand_matches_path) %>
	<%= link_to "Upload new match list", upload_brand_matches_path, class: "btn btn-large btn-primary" %>
</div>

app/views/brand_matches/_form.html.erb
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@brand_match) do |f| %>
			<%= render 'shared/error_messages', obj:@brand_match %>

			<div class="field">
				<%= f.label 'Match list (put each on a new line)' %>
				<%= f.text_area :match_list %>
			</div>
			<div class="field">
				<%= f.label 'Exclude list (put each on a new line)' %>
				<%= f.text_area :exclude_list %>
			</div>
			<div class="actions">
				<%= f.submit lbl, class:'btn btn-large btn-primary' %>
			</div>
		<% end %>
	</div>
</div>

app/views/brand_matches/edit.html.erb
<%= provide(:title, 'Change brand match') %>
<h1>Change brand match</h1>

<%= render 'form', lbl:'Save changes' %>

app/views/brand_matches/index.html.erb
<%= provide(:title, 'All brand matches') %>

<div id="save-alert" class="alert alert-success"></div>
<h1>All brand matches</h1>
<p>The priority order of the match list can be sorted using drag &amp; drop. Just click "Save sort order" to save your changes.</p>

<%= render 'button-nav' %>

<table class="data sortable" cellpadding="0" cellspacing="0" border="0">
	<thead>
		<tr>
			<th>Match</th>
			<th>Match list</th>
			<th>Exclude list</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<%= render @brand_matches %>
	</tbody>
</table>

<%= render 'button-nav' %>

app/views/brand_matches/new.html.erb
<%= provide(:title, 'Add new match') %>
<h1>Add new match</h1>

<%= render 'form', lbl:'Add match' %>

app/views/brand_matches/upload.html.erb
<% provide(:title, "Upload new brand match file") %>
<h1>Upload new brand match file</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_tag(process_upload_brand_matches_path, multipart:true) do %>
			<%= render 'shared/error_messages', obj:@upload_file %>

			<div class="field">
				<%= label_tag "upload_file_filename", "Upload CSV file", class:"inline" %>&nbsp;(<%= link_to "see template", "/templates/brand_matches.csv" %>)
				<%= file_field 'upload_file', 'filename' %>
			</div>
		
			<div class="action">
				<%= submit_tag("Upload file", class: "btn btn-large btn-primary") %>
			</div>
		<% end %>
	</div>
</div>