config/routes.rb
Saint::Application.routes.draw do

  match '/signin',		to: 'sessions#new'
  match '/signout',		to: 'sessions#destroy', via: :delete
  match '/dashboard',	to: 'dashboard_trended_metrics#index'

  resources :cloud_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end

  resources :clouds

  resources :brand_matches do
    collection do
      get 'upload'
      post 'process_upload'
      post 'sort'
    end
  end
  
  resources :classifications do
    collection do
      get 'run'
    end
    member do
      get 'run'
    end
  end
  
  resources :sites

  resources :suites
  
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :dashboard_trended_metrics do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_driver_types do
    collection do
      get 'visits'
      get 'form_completes'
    end
  end
  
  resources :dashboard_browsers do
    collection do
      get 'visits'
    end
  end
  
  resources :dashboard_clouds do
    collection do
      get 'page_views'
      get 'form_completes'
    end
  end
  
  resources :dashboard_offer_types do
    collection do
      get 'form_views'
      get 'form_completes'
      get 'form_complete_rate'
    end
  end
  
  resources :dashboard_video_names do
    collection do
      get 'video_starts'
      get 'video_completes'
    end
  end
  
  root :to => 'classifications#index'

end

app/models/dashboard_trended_metric.rb
class DashboardTrendedMetric < ActiveRecord::Base
  validates :date, presence:true
  validates :visits, presence:true
  validates :form_completes, presence:true
end

app/controllers/dashboard_trended_metrics_controller.rb
class DashboardTrendedMetricsController < ApplicationController
  def visits
    load if !is_current_data?
    
    @dashboard_trended_metrics = DashboardTrendedMetric.find(:all, :order => "date DESC")
    
    respond_to do |format|
      format.html { }
      format.json {
        render :json => @dashboard_trended_metrics
      }
    end
  end
  
  def form_completes
    load if !is_current_data?
    
    @dashboard_trended_metrics = DashboardTrendedMetric.find(:all, :order => "date DESC")
    
    respond_to do |format|
      format.html { }
      format.json {
        render :json => @dashboard_trended_metrics
      }
    end
  end
  
  def is_current_data?
    if DashboardTrendedMetric.all.length == 0
      cur = false
    elsif DashboardTrendedMetric.maximum(:date) < 2.days.ago.to_date
      cur = false
    else
      cur = true
    end
    
    cur
  end
  
  def load
    require 'omni'
    
    suite_id = "salesforcemarketing"
    t_end = Time.new.to_date - 2
    t_start = t_end - 59
    metrics = [
      {"id" => "visits"},
      {"id" => "event17"}
    ]
    segment = "dsc:280:228:c221f926-19c8-4430-b9b0-56d6095bd6b4"
    granularity = "day"
    
    o = Omni.new
    if Rails.env.production?
      o.delay.load_trended_metrics(suite_id, metrics, segment, t_start, t_end, granularity)
    else
      o.load_trended_metrics(suite_id, metrics, segment, t_start, t_end, granularity)
    end
  end
end

app/views/dashboard_trended_metrics/form_completes.html.erb
<%= provide(:title, 'Form Completes') %>
<h1>Form Completes</h1>

<div class="button-nav">
	<%= link_to "Back to dashboard home", dashboard_trended_metrics_path, class: "btn btn-large btn-primary" %>
</div>

<%  count = 0
    max = 30
    @dashboard_trended_metrics.each do |km|
      if count % max == 0
        if count != 0 %>
	</table>
</div>
<%      end %>
<div style="width: 50%; float: left;">
<%      if count == 0 %>
	<h3>30 Days Prior</h3>
<%      else %>
	<h3>Last 30 days</h3>
<%      end %>
	<table class="data" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<th>Date</th>
			<th>Form Completes</th>
		</tr>
<%    end
      count += 1 %>
		<tr>
			<td><%= km.date.strftime("%-m/%-d/%Y") %></td>
			<td><%= km.form_completes %></td>
		</tr>
<%  end %>
	</table>
</div>

<div class="button-nav">
	<%= link_to "Back to dashboard home", dashboard_trended_metrics_path, class: "btn btn-large btn-primary" %>
</div>

app/views/dashboard_trended_metrics/index.html.erb
<%= provide(:title, 'Dashboard') %>
<h1>Dashboard links</h1>

<ul>
	<li><%= link_to "Visits", visits_dashboard_trended_metrics_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_trended_metrics/visits.json" %></li>
	<li><%= link_to "Form Completes", form_completes_dashboard_trended_metrics_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_trended_metrics/form_completes.json" %></li>
	<li><%= link_to "Visits by Browser/Device", visits_dashboard_browsers_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_browsers/visits.json" %></li>
	<li><%= link_to "Traffic Driver Types (Visits)", visits_dashboard_driver_types_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_driver_types/visits.json" %></li>
	<li><%= link_to "Traffic Driver Types (Form Completes)", form_completes_dashboard_driver_types_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_driver_types/form_completes.json" %></li>
	<li><%= link_to "Page Cloud (Page Views)", page_views_dashboard_clouds_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_clouds/page_views.json" %></li>
	<li><%= link_to "Page Cloud (Form Completes)", form_completes_dashboard_clouds_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_clouds/form_completes.json" %></li>
	<li><%= link_to "Videos (Video Starts)", video_starts_dashboard_video_names_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_video_names/video_starts.json" %></li>
	<li><%= link_to "Videos (Video Completes)", video_completes_dashboard_video_names_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_video_names/video_completes.json" %></li>
	<li><%= link_to "Offer Type (Form Views)", form_views_dashboard_offer_types_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_offer_types/form_views.json" %></li>
	<li><%= link_to "Offer Type (Form Completes)", form_completes_dashboard_offer_types_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_offer_types/form_completes.json" %></li>
	<li><%= link_to "Offer Type (Form Completion Rate)", form_complete_rate_dashboard_offer_types_path %>&nbsp;|&nbsp;<%= link_to "JSON", "/dashboard_offer_types/form_complete_rate.json" %></li>
</ul>

app/views/dashboard_trended_metrics/visits.html.erb
<%= @t_start %>
<br><%= @t_end %>
<%= provide(:title, 'Visits') %>
<h1>Visits</h1>

<div class="button-nav">
	<%= link_to "Back to dashboard home", dashboard_trended_metrics_path, class: "btn btn-large btn-primary" %>
</div>

<%  count = 0
    max = 30
    @dashboard_trended_metrics.each do |km|
      if count % max == 0
        if count != 0 %>
	</table>
</div>
<%      end %>
<div style="width: 50%; float: left;">
<%      if count == 0 %>
	<h3>30 Days Prior</h3>
<%      else %>
	<h3>Last 30 days</h3>
<%      end %>
	<table class="data" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<th>Date</th>
			<th>Visits</th>
		</tr>
<%    end
      count += 1 %>
		<tr>
			<td><%= km.date.strftime("%-m/%-d/%Y") %></td>
			<td><%= km.visits %></td>
		</tr>
<%  end %>
	</table>
</div>

<div class="button-nav">
	<%= link_to "Back to dashboard home", dashboard_trended_metrics_path, class: "btn btn-large btn-primary" %>
</div>